apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: preemptible-address-controller
  name: preemptible-address-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preemptible-address-controller
  template:
    metadata:
      labels:
        app: preemptible-address-controller
    spec:
      containers:
        - args:
            - --address-label=mangaka.tech/use-address
            - --address-name=mangaka-instance
          image: quay.io/tsuruda/preemptible-address-controller
          imagePullPolicy: Always
          name: debug
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/secrets/google
              name: google-cloud-key
      volumes:
        - name: google-cloud-key
          secret:
            defaultMode: 420
            secretName: preemptible-address-controller
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: preemptible-address-controller
